//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletAllReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BiletAllReference.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlIslet", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.XmlIsletResponse> XmlIsletAsync(BiletAllReference.XmlIsletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrIslet", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.StrIsletResponse> StrIsletAsync(BiletAllReference.StrIsletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OtobusKalkis", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.OtobusKalkisResponse> OtobusKalkisAsync(BiletAllReference.OtobusKalkisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDOKalkis", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.IDOKalkisResponse> IDOKalkisAsync(BiletAllReference.IDOKalkisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDOVaris", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.IDOVarisResponse> IDOVarisAsync(BiletAllReference.IDOVarisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrenNokta", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.TrenNoktaResponse> TrenNoktaAsync(BiletAllReference.TrenNoktaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HavaAlan", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.HavaAlanResponse> HavaAlanAsync(BiletAllReference.HavaAlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResmiTatilGunleri", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.ResmiTatilGunleriResponse> ResmiTatilGunleriAsync(BiletAllReference.ResmiTatilGunleriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnYakinHavaNoktaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.EnYakinHavaNoktaGetirResponse> EnYakinHavaNoktaGetirAsync(BiletAllReference.EnYakinHavaNoktaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/strEnYakinHavaNoktaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.strEnYakinHavaNoktaGetirResponse> strEnYakinHavaNoktaGetirAsync(BiletAllReference.strEnYakinHavaNoktaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnYakinKaraNoktaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.EnYakinKaraNoktaGetirResponse> EnYakinKaraNoktaGetirAsync(BiletAllReference.EnYakinKaraNoktaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/strEnYakinKaraNoktaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.strEnYakinKaraNoktaGetirResponse> strEnYakinKaraNoktaGetirAsync(BiletAllReference.strEnYakinKaraNoktaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CiftBiletKontrolEt", ReplyAction="*")]
        System.Threading.Tasks.Task<BiletAllReference.CiftBiletKontrolEtResponse> CiftBiletKontrolEtAsync(BiletAllReference.CiftBiletKontrolEtRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlIsletRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlIslet", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.XmlIsletRequestBody Body;
        
        public XmlIsletRequest()
        {
        }
        
        public XmlIsletRequest(BiletAllReference.XmlIsletRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlIsletRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement xmlIslem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.XmlElement xmlYetki;
        
        public XmlIsletRequestBody()
        {
        }
        
        public XmlIsletRequestBody(System.Xml.XmlElement xmlIslem, System.Xml.XmlElement xmlYetki)
        {
            this.xmlIslem = xmlIslem;
            this.xmlYetki = xmlYetki;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlIsletResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlIsletResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.XmlIsletResponseBody Body;
        
        public XmlIsletResponse()
        {
        }
        
        public XmlIsletResponse(BiletAllReference.XmlIsletResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlIsletResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement XmlIsletResult;
        
        public XmlIsletResponseBody()
        {
        }
        
        public XmlIsletResponseBody(System.Xml.XmlElement XmlIsletResult)
        {
            this.XmlIsletResult = XmlIsletResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrIsletRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StrIslet", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.StrIsletRequestBody Body;
        
        public StrIsletRequest()
        {
        }
        
        public StrIsletRequest(BiletAllReference.StrIsletRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StrIsletRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strislem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stryetki;
        
        public StrIsletRequestBody()
        {
        }
        
        public StrIsletRequestBody(string strislem, string stryetki)
        {
            this.strislem = strislem;
            this.stryetki = stryetki;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrIsletResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StrIsletResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.StrIsletResponseBody Body;
        
        public StrIsletResponse()
        {
        }
        
        public StrIsletResponse(BiletAllReference.StrIsletResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StrIsletResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StrIsletResult;
        
        public StrIsletResponseBody()
        {
        }
        
        public StrIsletResponseBody(string StrIsletResult)
        {
            this.StrIsletResult = StrIsletResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OtobusKalkisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OtobusKalkis", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.OtobusKalkisRequestBody Body;
        
        public OtobusKalkisRequest()
        {
        }
        
        public OtobusKalkisRequest(BiletAllReference.OtobusKalkisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OtobusKalkisRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ilcelerGetirilsinMi;
        
        public OtobusKalkisRequestBody()
        {
        }
        
        public OtobusKalkisRequestBody(string ilcelerGetirilsinMi)
        {
            this.ilcelerGetirilsinMi = ilcelerGetirilsinMi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OtobusKalkisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OtobusKalkisResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.OtobusKalkisResponseBody Body;
        
        public OtobusKalkisResponse()
        {
        }
        
        public OtobusKalkisResponse(BiletAllReference.OtobusKalkisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OtobusKalkisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement OtobusKalkisResult;
        
        public OtobusKalkisResponseBody()
        {
        }
        
        public OtobusKalkisResponseBody(System.Xml.XmlElement OtobusKalkisResult)
        {
            this.OtobusKalkisResult = OtobusKalkisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDOKalkisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDOKalkis", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.IDOKalkisRequestBody Body;
        
        public IDOKalkisRequest()
        {
        }
        
        public IDOKalkisRequest(BiletAllReference.IDOKalkisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IDOKalkisRequestBody
    {
        
        public IDOKalkisRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDOKalkisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDOKalkisResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.IDOKalkisResponseBody Body;
        
        public IDOKalkisResponse()
        {
        }
        
        public IDOKalkisResponse(BiletAllReference.IDOKalkisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IDOKalkisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement IDOKalkisResult;
        
        public IDOKalkisResponseBody()
        {
        }
        
        public IDOKalkisResponseBody(System.Xml.XmlElement IDOKalkisResult)
        {
            this.IDOKalkisResult = IDOKalkisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDOVarisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDOVaris", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.IDOVarisRequestBody Body;
        
        public IDOVarisRequest()
        {
        }
        
        public IDOVarisRequest(BiletAllReference.IDOVarisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IDOVarisRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public IDOVarisRequestBody()
        {
        }
        
        public IDOVarisRequestBody(string key)
        {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDOVarisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDOVarisResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.IDOVarisResponseBody Body;
        
        public IDOVarisResponse()
        {
        }
        
        public IDOVarisResponse(BiletAllReference.IDOVarisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IDOVarisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement IDOVarisResult;
        
        public IDOVarisResponseBody()
        {
        }
        
        public IDOVarisResponseBody(System.Xml.XmlElement IDOVarisResult)
        {
            this.IDOVarisResult = IDOVarisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrenNoktaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrenNokta", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.TrenNoktaRequestBody Body;
        
        public TrenNoktaRequest()
        {
        }
        
        public TrenNoktaRequest(BiletAllReference.TrenNoktaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TrenNoktaRequestBody
    {
        
        public TrenNoktaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrenNoktaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrenNoktaResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.TrenNoktaResponseBody Body;
        
        public TrenNoktaResponse()
        {
        }
        
        public TrenNoktaResponse(BiletAllReference.TrenNoktaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrenNoktaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement TrenNoktaResult;
        
        public TrenNoktaResponseBody()
        {
        }
        
        public TrenNoktaResponseBody(System.Xml.XmlElement TrenNoktaResult)
        {
            this.TrenNoktaResult = TrenNoktaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HavaAlanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HavaAlan", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.HavaAlanRequestBody Body;
        
        public HavaAlanRequest()
        {
        }
        
        public HavaAlanRequest(BiletAllReference.HavaAlanRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HavaAlanRequestBody
    {
        
        public HavaAlanRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HavaAlanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HavaAlanResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.HavaAlanResponseBody Body;
        
        public HavaAlanResponse()
        {
        }
        
        public HavaAlanResponse(BiletAllReference.HavaAlanResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HavaAlanResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement HavaAlanResult;
        
        public HavaAlanResponseBody()
        {
        }
        
        public HavaAlanResponseBody(System.Xml.XmlElement HavaAlanResult)
        {
            this.HavaAlanResult = HavaAlanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResmiTatilGunleriRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResmiTatilGunleri", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.ResmiTatilGunleriRequestBody Body;
        
        public ResmiTatilGunleriRequest()
        {
        }
        
        public ResmiTatilGunleriRequest(BiletAllReference.ResmiTatilGunleriRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResmiTatilGunleriRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string yil;
        
        public ResmiTatilGunleriRequestBody()
        {
        }
        
        public ResmiTatilGunleriRequestBody(string yil)
        {
            this.yil = yil;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResmiTatilGunleriResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResmiTatilGunleriResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.ResmiTatilGunleriResponseBody Body;
        
        public ResmiTatilGunleriResponse()
        {
        }
        
        public ResmiTatilGunleriResponse(BiletAllReference.ResmiTatilGunleriResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResmiTatilGunleriResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ResmiTatilGunleriResult;
        
        public ResmiTatilGunleriResponseBody()
        {
        }
        
        public ResmiTatilGunleriResponseBody(System.Xml.XmlElement ResmiTatilGunleriResult)
        {
            this.ResmiTatilGunleriResult = ResmiTatilGunleriResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnYakinHavaNoktaGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnYakinHavaNoktaGetir", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.EnYakinHavaNoktaGetirRequestBody Body;
        
        public EnYakinHavaNoktaGetirRequest()
        {
        }
        
        public EnYakinHavaNoktaGetirRequest(BiletAllReference.EnYakinHavaNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnYakinHavaNoktaGetirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string karaNokta;
        
        public EnYakinHavaNoktaGetirRequestBody()
        {
        }
        
        public EnYakinHavaNoktaGetirRequestBody(string karaNokta)
        {
            this.karaNokta = karaNokta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnYakinHavaNoktaGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnYakinHavaNoktaGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.EnYakinHavaNoktaGetirResponseBody Body;
        
        public EnYakinHavaNoktaGetirResponse()
        {
        }
        
        public EnYakinHavaNoktaGetirResponse(BiletAllReference.EnYakinHavaNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnYakinHavaNoktaGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement EnYakinHavaNoktaGetirResult;
        
        public EnYakinHavaNoktaGetirResponseBody()
        {
        }
        
        public EnYakinHavaNoktaGetirResponseBody(System.Xml.XmlElement EnYakinHavaNoktaGetirResult)
        {
            this.EnYakinHavaNoktaGetirResult = EnYakinHavaNoktaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class strEnYakinHavaNoktaGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="strEnYakinHavaNoktaGetir", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.strEnYakinHavaNoktaGetirRequestBody Body;
        
        public strEnYakinHavaNoktaGetirRequest()
        {
        }
        
        public strEnYakinHavaNoktaGetirRequest(BiletAllReference.strEnYakinHavaNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class strEnYakinHavaNoktaGetirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string karaNokta;
        
        public strEnYakinHavaNoktaGetirRequestBody()
        {
        }
        
        public strEnYakinHavaNoktaGetirRequestBody(string karaNokta)
        {
            this.karaNokta = karaNokta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class strEnYakinHavaNoktaGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="strEnYakinHavaNoktaGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.strEnYakinHavaNoktaGetirResponseBody Body;
        
        public strEnYakinHavaNoktaGetirResponse()
        {
        }
        
        public strEnYakinHavaNoktaGetirResponse(BiletAllReference.strEnYakinHavaNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class strEnYakinHavaNoktaGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEnYakinHavaNoktaGetirResult;
        
        public strEnYakinHavaNoktaGetirResponseBody()
        {
        }
        
        public strEnYakinHavaNoktaGetirResponseBody(string strEnYakinHavaNoktaGetirResult)
        {
            this.strEnYakinHavaNoktaGetirResult = strEnYakinHavaNoktaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnYakinKaraNoktaGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnYakinKaraNoktaGetir", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.EnYakinKaraNoktaGetirRequestBody Body;
        
        public EnYakinKaraNoktaGetirRequest()
        {
        }
        
        public EnYakinKaraNoktaGetirRequest(BiletAllReference.EnYakinKaraNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnYakinKaraNoktaGetirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string havaKod;
        
        public EnYakinKaraNoktaGetirRequestBody()
        {
        }
        
        public EnYakinKaraNoktaGetirRequestBody(string havaKod)
        {
            this.havaKod = havaKod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnYakinKaraNoktaGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnYakinKaraNoktaGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.EnYakinKaraNoktaGetirResponseBody Body;
        
        public EnYakinKaraNoktaGetirResponse()
        {
        }
        
        public EnYakinKaraNoktaGetirResponse(BiletAllReference.EnYakinKaraNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnYakinKaraNoktaGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnYakinKaraNoktaGetirResult;
        
        public EnYakinKaraNoktaGetirResponseBody()
        {
        }
        
        public EnYakinKaraNoktaGetirResponseBody(string EnYakinKaraNoktaGetirResult)
        {
            this.EnYakinKaraNoktaGetirResult = EnYakinKaraNoktaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class strEnYakinKaraNoktaGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="strEnYakinKaraNoktaGetir", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.strEnYakinKaraNoktaGetirRequestBody Body;
        
        public strEnYakinKaraNoktaGetirRequest()
        {
        }
        
        public strEnYakinKaraNoktaGetirRequest(BiletAllReference.strEnYakinKaraNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class strEnYakinKaraNoktaGetirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string havaKod;
        
        public strEnYakinKaraNoktaGetirRequestBody()
        {
        }
        
        public strEnYakinKaraNoktaGetirRequestBody(string havaKod)
        {
            this.havaKod = havaKod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class strEnYakinKaraNoktaGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="strEnYakinKaraNoktaGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.strEnYakinKaraNoktaGetirResponseBody Body;
        
        public strEnYakinKaraNoktaGetirResponse()
        {
        }
        
        public strEnYakinKaraNoktaGetirResponse(BiletAllReference.strEnYakinKaraNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class strEnYakinKaraNoktaGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEnYakinKaraNoktaGetirResult;
        
        public strEnYakinKaraNoktaGetirResponseBody()
        {
        }
        
        public strEnYakinKaraNoktaGetirResponseBody(string strEnYakinKaraNoktaGetirResult)
        {
            this.strEnYakinKaraNoktaGetirResult = strEnYakinKaraNoktaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CiftBiletKontrolEtRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CiftBiletKontrolEt", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.CiftBiletKontrolEtRequestBody Body;
        
        public CiftBiletKontrolEtRequest()
        {
        }
        
        public CiftBiletKontrolEtRequest(BiletAllReference.CiftBiletKontrolEtRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CiftBiletKontrolEtRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string islem;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int firmaNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime tarih;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string kalkis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string varis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string yolcuAd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string yolcuSoyad;
        
        public CiftBiletKontrolEtRequestBody()
        {
        }
        
        public CiftBiletKontrolEtRequestBody(string islem, int firmaNo, System.DateTime tarih, string kalkis, string varis, string yolcuAd, string yolcuSoyad)
        {
            this.islem = islem;
            this.firmaNo = firmaNo;
            this.tarih = tarih;
            this.kalkis = kalkis;
            this.varis = varis;
            this.yolcuAd = yolcuAd;
            this.yolcuSoyad = yolcuSoyad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CiftBiletKontrolEtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CiftBiletKontrolEtResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiletAllReference.CiftBiletKontrolEtResponseBody Body;
        
        public CiftBiletKontrolEtResponse()
        {
        }
        
        public CiftBiletKontrolEtResponse(BiletAllReference.CiftBiletKontrolEtResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CiftBiletKontrolEtResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CiftBiletKontrolEtResult;
        
        public CiftBiletKontrolEtResponseBody()
        {
        }
        
        public CiftBiletKontrolEtResponseBody(string CiftBiletKontrolEtResult)
        {
            this.CiftBiletKontrolEtResult = CiftBiletKontrolEtResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ServiceSoapChannel : BiletAllReference.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BiletAllReference.ServiceSoap>, BiletAllReference.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.XmlIsletResponse> BiletAllReference.ServiceSoap.XmlIsletAsync(BiletAllReference.XmlIsletRequest request)
        {
            return base.Channel.XmlIsletAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.XmlIsletResponse> XmlIsletAsync(System.Xml.XmlElement xmlIslem, System.Xml.XmlElement xmlYetki)
        {
            BiletAllReference.XmlIsletRequest inValue = new BiletAllReference.XmlIsletRequest();
            inValue.Body = new BiletAllReference.XmlIsletRequestBody();
            inValue.Body.xmlIslem = xmlIslem;
            inValue.Body.xmlYetki = xmlYetki;
            return ((BiletAllReference.ServiceSoap)(this)).XmlIsletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.StrIsletResponse> BiletAllReference.ServiceSoap.StrIsletAsync(BiletAllReference.StrIsletRequest request)
        {
            return base.Channel.StrIsletAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.StrIsletResponse> StrIsletAsync(string strislem, string stryetki)
        {
            BiletAllReference.StrIsletRequest inValue = new BiletAllReference.StrIsletRequest();
            inValue.Body = new BiletAllReference.StrIsletRequestBody();
            inValue.Body.strislem = strislem;
            inValue.Body.stryetki = stryetki;
            return ((BiletAllReference.ServiceSoap)(this)).StrIsletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.OtobusKalkisResponse> BiletAllReference.ServiceSoap.OtobusKalkisAsync(BiletAllReference.OtobusKalkisRequest request)
        {
            return base.Channel.OtobusKalkisAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.OtobusKalkisResponse> OtobusKalkisAsync(string ilcelerGetirilsinMi)
        {
            BiletAllReference.OtobusKalkisRequest inValue = new BiletAllReference.OtobusKalkisRequest();
            inValue.Body = new BiletAllReference.OtobusKalkisRequestBody();
            inValue.Body.ilcelerGetirilsinMi = ilcelerGetirilsinMi;
            return ((BiletAllReference.ServiceSoap)(this)).OtobusKalkisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.IDOKalkisResponse> BiletAllReference.ServiceSoap.IDOKalkisAsync(BiletAllReference.IDOKalkisRequest request)
        {
            return base.Channel.IDOKalkisAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.IDOKalkisResponse> IDOKalkisAsync()
        {
            BiletAllReference.IDOKalkisRequest inValue = new BiletAllReference.IDOKalkisRequest();
            inValue.Body = new BiletAllReference.IDOKalkisRequestBody();
            return ((BiletAllReference.ServiceSoap)(this)).IDOKalkisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.IDOVarisResponse> BiletAllReference.ServiceSoap.IDOVarisAsync(BiletAllReference.IDOVarisRequest request)
        {
            return base.Channel.IDOVarisAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.IDOVarisResponse> IDOVarisAsync(string key)
        {
            BiletAllReference.IDOVarisRequest inValue = new BiletAllReference.IDOVarisRequest();
            inValue.Body = new BiletAllReference.IDOVarisRequestBody();
            inValue.Body.key = key;
            return ((BiletAllReference.ServiceSoap)(this)).IDOVarisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.TrenNoktaResponse> BiletAllReference.ServiceSoap.TrenNoktaAsync(BiletAllReference.TrenNoktaRequest request)
        {
            return base.Channel.TrenNoktaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.TrenNoktaResponse> TrenNoktaAsync()
        {
            BiletAllReference.TrenNoktaRequest inValue = new BiletAllReference.TrenNoktaRequest();
            inValue.Body = new BiletAllReference.TrenNoktaRequestBody();
            return ((BiletAllReference.ServiceSoap)(this)).TrenNoktaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.HavaAlanResponse> BiletAllReference.ServiceSoap.HavaAlanAsync(BiletAllReference.HavaAlanRequest request)
        {
            return base.Channel.HavaAlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.HavaAlanResponse> HavaAlanAsync()
        {
            BiletAllReference.HavaAlanRequest inValue = new BiletAllReference.HavaAlanRequest();
            inValue.Body = new BiletAllReference.HavaAlanRequestBody();
            return ((BiletAllReference.ServiceSoap)(this)).HavaAlanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.ResmiTatilGunleriResponse> BiletAllReference.ServiceSoap.ResmiTatilGunleriAsync(BiletAllReference.ResmiTatilGunleriRequest request)
        {
            return base.Channel.ResmiTatilGunleriAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.ResmiTatilGunleriResponse> ResmiTatilGunleriAsync(string yil)
        {
            BiletAllReference.ResmiTatilGunleriRequest inValue = new BiletAllReference.ResmiTatilGunleriRequest();
            inValue.Body = new BiletAllReference.ResmiTatilGunleriRequestBody();
            inValue.Body.yil = yil;
            return ((BiletAllReference.ServiceSoap)(this)).ResmiTatilGunleriAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.EnYakinHavaNoktaGetirResponse> BiletAllReference.ServiceSoap.EnYakinHavaNoktaGetirAsync(BiletAllReference.EnYakinHavaNoktaGetirRequest request)
        {
            return base.Channel.EnYakinHavaNoktaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.EnYakinHavaNoktaGetirResponse> EnYakinHavaNoktaGetirAsync(string karaNokta)
        {
            BiletAllReference.EnYakinHavaNoktaGetirRequest inValue = new BiletAllReference.EnYakinHavaNoktaGetirRequest();
            inValue.Body = new BiletAllReference.EnYakinHavaNoktaGetirRequestBody();
            inValue.Body.karaNokta = karaNokta;
            return ((BiletAllReference.ServiceSoap)(this)).EnYakinHavaNoktaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.strEnYakinHavaNoktaGetirResponse> BiletAllReference.ServiceSoap.strEnYakinHavaNoktaGetirAsync(BiletAllReference.strEnYakinHavaNoktaGetirRequest request)
        {
            return base.Channel.strEnYakinHavaNoktaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.strEnYakinHavaNoktaGetirResponse> strEnYakinHavaNoktaGetirAsync(string karaNokta)
        {
            BiletAllReference.strEnYakinHavaNoktaGetirRequest inValue = new BiletAllReference.strEnYakinHavaNoktaGetirRequest();
            inValue.Body = new BiletAllReference.strEnYakinHavaNoktaGetirRequestBody();
            inValue.Body.karaNokta = karaNokta;
            return ((BiletAllReference.ServiceSoap)(this)).strEnYakinHavaNoktaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.EnYakinKaraNoktaGetirResponse> BiletAllReference.ServiceSoap.EnYakinKaraNoktaGetirAsync(BiletAllReference.EnYakinKaraNoktaGetirRequest request)
        {
            return base.Channel.EnYakinKaraNoktaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.EnYakinKaraNoktaGetirResponse> EnYakinKaraNoktaGetirAsync(string havaKod)
        {
            BiletAllReference.EnYakinKaraNoktaGetirRequest inValue = new BiletAllReference.EnYakinKaraNoktaGetirRequest();
            inValue.Body = new BiletAllReference.EnYakinKaraNoktaGetirRequestBody();
            inValue.Body.havaKod = havaKod;
            return ((BiletAllReference.ServiceSoap)(this)).EnYakinKaraNoktaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.strEnYakinKaraNoktaGetirResponse> BiletAllReference.ServiceSoap.strEnYakinKaraNoktaGetirAsync(BiletAllReference.strEnYakinKaraNoktaGetirRequest request)
        {
            return base.Channel.strEnYakinKaraNoktaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.strEnYakinKaraNoktaGetirResponse> strEnYakinKaraNoktaGetirAsync(string havaKod)
        {
            BiletAllReference.strEnYakinKaraNoktaGetirRequest inValue = new BiletAllReference.strEnYakinKaraNoktaGetirRequest();
            inValue.Body = new BiletAllReference.strEnYakinKaraNoktaGetirRequestBody();
            inValue.Body.havaKod = havaKod;
            return ((BiletAllReference.ServiceSoap)(this)).strEnYakinKaraNoktaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiletAllReference.CiftBiletKontrolEtResponse> BiletAllReference.ServiceSoap.CiftBiletKontrolEtAsync(BiletAllReference.CiftBiletKontrolEtRequest request)
        {
            return base.Channel.CiftBiletKontrolEtAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiletAllReference.CiftBiletKontrolEtResponse> CiftBiletKontrolEtAsync(string islem, int firmaNo, System.DateTime tarih, string kalkis, string varis, string yolcuAd, string yolcuSoyad)
        {
            BiletAllReference.CiftBiletKontrolEtRequest inValue = new BiletAllReference.CiftBiletKontrolEtRequest();
            inValue.Body = new BiletAllReference.CiftBiletKontrolEtRequestBody();
            inValue.Body.islem = islem;
            inValue.Body.firmaNo = firmaNo;
            inValue.Body.tarih = tarih;
            inValue.Body.kalkis = kalkis;
            inValue.Body.varis = varis;
            inValue.Body.yolcuAd = yolcuAd;
            inValue.Body.yolcuSoyad = yolcuSoyad;
            return ((BiletAllReference.ServiceSoap)(this)).CiftBiletKontrolEtAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://62.248.56.228/WSTEST/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://62.248.56.228/WSTEST/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
